services:
  bitcoin:
    build: ./bitcoin
    container_name: bitcoin
    volumes:
      - bitcoin_node1:/workspace/bitcoin/node1
      - bitcoin_node2:/workspace/bitcoin/node2
    env_file: .env
    networks:
      - corecraft

  corecraft-v1:
    build: ./atividade-1
    container_name: corecraft-v1
    ports:
      - "3000:3000"
    volumes:
      - ./atividade-1:/app
      - bundle_cache:/usr/local/bundle
    env_file:
      - ./atividade-1/.env.${RAILS_ENV:-development}
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
    networks:
      - corecraft

  corecraft-v2:
    build: ./atividade-2
    container_name: corecraft-v2
    ports:
      - "3000:3000"
    volumes:
      - ./atividade-2:/app
      - bundle_cache_v2:/usr/local/bundle
    env_file:
      - ./atividade-2/.env.${RAILS_ENV:-development}
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}
    networks:
      - corecraft

volumes:
  bundle_cache:
  bundle_cache_v2:
  bitcoin_node1:
  bitcoin_node2:

networks:
  corecraft:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
